default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 1234
  timeout: 5000

development:
  <<: *default
  database: cumplo_test_development

test: &test
  <<: *default
  database: cumplo_test_test

production:
  <<: *default
  database: cumplo_test_production

cucumber:
  <<: *test
